version: '3.8'

services:
  war_api:
    build:
      context: .
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
  db:
    image: mysql:8.2
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=war_api
      - MYSQL_USERNAME=war_api_user
      - MYSQL_PASSWORD=war_api_pass
    ports:
      - 3306:3306
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
volumes:
  db-data:
    driver: local
networks:
  default:
    driver: bridge

