name: "CI workflow"

on: 
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.2
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: Copy ENV 
        run: cp .env.ci .env
      - name: Install dependencies
        run: | 
          poetry --version
          poetry check --no-interaction
          poetry config virtualenvs.create false
          poetry install --no-interaction
      - name: Testing
        run: pytest

      